language: rust
cache: cargo

DEPLOY_TO_GITHUB: &DEPLOY_TO_GITHUB
  before_deploy:
    - git config --local user.name "deweycw"
    - git config --local user.email "dewey.christian@gmail.com"
    - name="cms-$TRAVIS_TAG-$TARGET"
    - mkdir $name
    - cp target/$TARGET/release/docker-rust $name/
    - tar czvf $name.tar.gz $name
  deploy:
    provider: releases
    file: cms_test-$TRAVIS_TAG-$TARGET.tar.gz
    skip_cleanup: true
    on:
      branch: releases
      tags: true


jobs: 
  include:
  - name: Linux Binary
    env: TARGET=x86_64-unknown-linux-musl
    rust: stable
    before_script:
      - rustup target add x86_64-unknown-linux-musl
    script: cargo build --release --target $TARGET
    <<: *DEPLOY_TO_GITHUB

  - name: OSX Binary
    env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    rust: stable
    script: cargo build --release --target $TARGET
    install: true
    <<: *DEPLOY_TO_GITHUB

  - name: Windows Binary
    env: TARGET=x86_64-pc-windows-gnu
    rust: stable
    before_script:
      - rustup target add x86_64-pc-windows-gnu
    script: cargo build --release --target $TARGET
    install: true
    <<: *DEPLOY_TO_GITHUB