services:
  dewey-molformdb:
    image: postgres
    restart: always
    volumes:
      - dewey-db-volume:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - POSTGRES_USER=coremsappdb
      - POSTGRES_PASSWORD=coremsapppnnl
      - POSTGRES_DB=coremsapp
      - COREMS_DATABASE_URL="postgresql+psycopg2://coremsappdb:coremsapppnnl@molformdb:5432/coremsapp"
      
  dewey-corems-cl:
    image: deweycw/corems-cli
    restart: always
    volumes:
      - type: bind
        source: ./
        target: /CoreMS/usrdata
    tty: True
        
volumes:
  dewey-db-volume:

